### PR TITLE
bash.asc auf deutsch uebersetzt

### PR DESCRIPTION
**Pull request by pastatopf**

### CODE REVIEW

**Comment by pastatopf** [comment]
@jnavila : Again our builds are failing. Before trying to fix it again, can you please check if the problem is in the build configuration? Thanks

**Comment by jnavila** [comment]
The build configuration hasn't been changed for a while. The build started to break with 95e8776a441c875ea6f50fbc8c800322d0a9bd03

I guess some of the changes introduced there broke the structure of the book...

**Comment by jnavila** [comment]
To track the origin of the issue:

1. copy Gemfile and Rakefile from progit/progit2-pub into your working copy
2. run "bundle update"
3. run "bundle exec rake book:build". The error is usually reproduced in your working copy.
4. open `progit_v0.html` in your browser and track where the document's structure starts to be upset. Find back in your source files the origin of the issue.

**Comment by pastatopf** [comment]
This Pull request will be deleted and a new one with jnavilas changes will be done

**Pull request closed without merging**
